### ISSUE TITLE
Record attributes support

### ISSUE THREAD

**Issue by markrity** [octodns/octodns-cloudflare#135]
Hi all,
I’ve noticed that Cloudflare supports [DNS Record Attributes](https://developers.cloudflare.com/dns/manage-dns-records/reference/record-attributes/) (e.g., priority, proxied, and other metadata) when creating or updating DNS records, as shown in [Cloudflare’s API documentation](https://developers.cloudflare.com/api/resources/dns/subresources/records/methods/create/).

Currently, it appears that these attributes aren’t supported in this provider/plugin. I’m wondering if this is a feature that aligns with the project’s overall needs and goals, especially since not all DNS providers support attributes or comments in the same way.

I’d be happy to help implement or contribute a PR for this functionality if there’s general interest or consensus on how it should be handled. Let me know what you think!

Thanks!

**Comment by ross** [comment]
Afaik all of those things are currently supported, through not well documented, e.g.

https://github.com/octodns/octodns-cloudflare/blob/6edf23f8b8612a91c7a116905a413a04b718be14/tests/test_octodns_provider_cloudflare.py#L34-L67

This record wouldn't make any sense, but this is an example of how they're used.

```yaml
www:
    octodns:
        cloudflare:
            auto-ttl: True
            comment: hello world
            proxied: True
            tags:
                - one
                - two
```
