### ISSUE TITLE
BUG: Tag and comment implementation does not seem right

### ISSUE THREAD

**Issue by derekmpage** [octodns/octodns-cloudflare#142]
Tags and Comments can be added at the answer level.
Here is how it looks in the Cloudflare UI

![Image](https://github.com/user-attachments/assets/7d22368b-8a77-44f4-84d2-7c0459e459c7)
![Image](https://github.com/user-attachments/assets/eb317ca7-d234-4ac7-8bf2-795649abb04a)

When running an octodns-dump of the zone to config Yaml we see this...

```
---
? ''
: - type: A
    values:
    - 151.101.1.xx
    - 151.101.129.xx

... 

bob:
  octodns:
    cloudflare:
      auto-ttl: true
      comment: dpage-comment2
      tags:
      - othertag2
      - tag2
  ttl: 300
  type: A
  values:
  - 151.101.193.xx
  - 151.101.65.xx
~                     
```

Here we see comment and tag context for  `octodns.cloudflare:` referenced in the yaml config at the nodes record level.
Therefore, tags and comments are lost for records that have more then one answer value.

Above yaml config we see there is no metadata for answer 151.101.65.xx value. (tag1) 

Next, we sync this config back up to cloudflare....  

```

********************************************************************************
* xxx.xx.
********************************************************************************
* config (YamlProvider)
*   Create <ARecord A 300, bob.xxx.xx., ['151.101.193.xx', '151.101.65.xx'], {'cloudflare': {'auto-ttl': True, 'comment': 'comment1', 'tags': ['tag1']}}> (cloudflare)
*   Summary: Creates=1, Updates=0, Deletes=0, Existing=4, Meta=False
********************************************************************************


2025-05-20T12:02:07  [140650804848448] INFO  YamlProvider[config] apply: making 1 changes to xxx.xx.
2025-05-20T12:02:07  [140650804848448] INFO  Manager sync:   1 total changes
```

Then after we dump again.... We see Things have changed to ( tag1 )....

```
 dpage@MA-dpage  ~/git/ops-octodns   OPS-73119/feature-helper-scripts ±  cat zones/kay.ac.yaml
---
? ''
: - type: A
    values:
    - 151.101.1.xx
    - 151.101.129.xx
...

bob:
  octodns:
    cloudflare:
      auto-ttl: true
      comment: comment1
      tags:
      - tag1
  ttl: 300
  type: A
  values:
  - 151.101.193.xx
  - 151.101.65.xx
```

The really strange thing is the UI did not get over written, which I don't quite understand yet.

![Image](https://github.com/user-attachments/assets/5ebabef1-c20e-4b31-934f-1be6a64df78b)

**Comment by ross** [comment]
Moved to octodns-cloudflare since it's specific to that provider. 

Not really sure what makes sense here since octoDNS doesn't have multiple objects for things to live on. If they were just merged into a single octoDNS record there's be no way to map them back out into the separate cf objects on which they belong. 

It could combine them in the dump (doesn't current) and then just push them all to the record (as it currently does) but i'd need to clean out the others. (this is based on assumptions of what it's doing b/c i don't remember the details from years ago w/o digging in)

At the very least it needs to say something is up and that it can't fully manage.

> The really strange thing is the UI did not get over written, which I don't quite understand yet.

It's likely b/c that value (and thus the record backing it) wasn't touched. Probably only the first one was.

**Comment by barnumbirr** [comment]
Hi @ross — I'd like to pick this up. I know it's closed as stale, but I think there's a clean, backward-compatible way to address it, including the "at the very least it needs to say something is up" minimum you called for. Sketch below; happy to open a PR if you're open to it.

## The constraint (agreeing with you)

octoDNS core has no per-value metadata slot — `Record.octodns` is record-level and A/AAAA values are plain strings (confirmed against octoDNS 1.20.0). So the only place per-value metadata can live is the provider-controlled `octodns.cloudflare` dict. The lever that makes it work: `_gen_key` already matches Cloudflare objects by **value/content**, not by comment/tags — so a value-keyed map lines up exactly with the existing diff logic.

## Proposal: an optional `values:` map inside `octodns.cloudflare`

Keyed by the value, overriding record-level metadata per value. Purely additive — every existing config keeps working untouched.

### The reporter's case

Two Fastly IPs under `bob`, each with its own metadata in the CF UI:

| Cloudflare object | comment | tags |
|---|---|---|
| `151.101.193.10` | `primary` | `tag1`, `cdn` |
| `151.101.65.10` | `failover` | `tag2`, `cdn` |

**Dump today (the bug)** — only the first object survives; `151.101.65.10`'s metadata is dropped:

```yaml
bob:
  octodns:
    cloudflare:
      comment: primary
      tags: [cdn, tag1]
  ttl: 300
  type: A
  values: [151.101.193.10, 151.101.65.10]
```

**Dump after the fix** — when values differ, emit a per-value map and omit the record-level default (there's no single default to put there). Round-trips losslessly:

```yaml
bob:
  octodns:
    cloudflare:
      values:
        151.101.193.10:
          comment: primary
          tags: [cdn, tag1]
        151.101.65.10:
          comment: failover
          tags: [cdn, tag2]
  ttl: 300
  type: A
  values: [151.101.193.10, 151.101.65.10]
```

### Authoring ergonomics — record-level default + sparse override

Record-level `comment`/`tags` remain the default for any value **not** in the map; a `values:` entry overrides only what it names:

```yaml
www:
  octodns:
    cloudflare:
      comment: managed-by-octodns      # default for both IPs
      tags: [team:web]
      values:
        203.0.113.9:                    # override just this one
          comment: legacy-box-do-not-reuse
          tags: [team:web, deprecated]
  ttl: 300
  type: A
  values: [203.0.113.8, 203.0.113.9]
```

Resolution per value `v`: `comment` = `values[v].comment` if set, else record-level `comment`, else none (same for `tags`). A per-value entry replaces the field it specifies — tags aren't merged with the record-level list.

### Backward compatible

- **Single value** → no map, nothing changes.
- **All values share the same metadata** → dump keeps today's record-level shorthand; no `values:` map emitted.

### TXT — the case you and @derekmpage flagged

Multiple TXT values that legitimately need different comments become expressible:

```yaml
'':
  octodns:
    cloudflare:
      values:
        ? google-site-verification=abc123
        : comment: Search Console
          tags: [verification]
        ? v=spf1 include:_spf.example.com ~all
        : comment: SPF record
          tags: [email]
  ttl: 300
  type: TXT
  values:
  - google-site-verification=abc123
  - v=spf1 include:_spf.example.com ~all
```

### The "say something is up" minimum

The map is keyed by value string, so the one thing it can't represent is two Cloudflare objects with the **same** value but different metadata. There the provider keeps the first and logs loudly on dump:

```
WARNING CloudflareProvider[cloudflare] bob.example.com. A: Cloudflare has 2
objects for value "151.101.193.10" with differing comment/tags; octoDNS
cannot represent per-object metadata for duplicate values — keeping the
first.
```

So representable differences round-trip via the map, and the un-representable remainder is surfaced rather than silently lost.

## Scope

Full support for the scalar-value types where a value is a clean map key: A, AAAA, TXT, NS, CNAME/ALIAS (single-value, map is a no-op), SPF, PTR. Structured-value types (MX, SRV, CAA, LOC, NAPTR) fall back to the current record-level behavior plus the warning — they rarely carry per-value comments in practice, and we can extend later if there's demand.

## Two open design calls I'd value your steer on

1. **Dump output when values differ** — I lean toward emitting the full `values:` map and dropping the record-level default (unambiguous, trivially round-trips), vs. keeping the most-common metadata as the record-level default and only mapping the outliers (terser but ambiguous).
2. **Per-value tags = replace, not merge** with the record-level list (simpler mental model).

If this direction sounds reasonable I'm glad to put up a PR with tests. Would you be open to reopening?

**Comment by ross** [comment]
> ## Proposal: an optional `values:` map inside `octodns.cloudflare`
> 
> Keyed by the value, overriding record-level metadata per value. Purely additive — every existing config keeps working untouched.

Funnily enough using either a list or dict to store per-value occurred to me while paging this past discussion back into my working memory. 


> ### TXT — the case you and [@derekmpage](https://github.com/derekmpage) flagged
> 
> Multiple TXT values that legitimately need different comments become expressible:

I think this is the main issue with keying by the value, it might work decently for simpler/shorter values like the examples, but would get messy quickly with longer TXT values.

The place where it'd more clearly fail (as mentioned later in the Scope section) is with complex multi-part values where there isn't an obvious key, e.g. MX, SRV, ... 

> ### The "say something is up" minimum
> 
> The map is keyed by value string, so the one thing it can't represent is two Cloudflare objects with the **same** value but different metadata. There the provider keeps the first and logs loudly on dump:

Off the top of my head i can't think of "normal" situations where values appear multiple times. It'd definitely be possible to create something on purpose like a TXT with the same string multiple times so it is an issue that could be hit.

> ## Scope
> 
> Full support for the scalar-value types where a value is a clean map key: A, AAAA, TXT, NS, CNAME/ALIAS (single-value, map is a no-op), SPF, PTR. Structured-value types (MX, SRV, CAA, LOC, NAPTR) fall back to the current record-level behavior plus the warning — they rarely carry per-value comments in practice, and we can extend later if there's demand.

I don't know that I agree that the structured-value types would be any less likely to have per-value comments or tags.

My first thought was to use lists where the comments/tags are matched up by order, but the downside to that would be it's fiddly to make changes and keep things matched up. 

> ## Two open design calls I'd value your steer on
> 
>     1. **Dump output when values differ** — I lean toward emitting the full `values:` map and dropping the record-level default (unambiguous, trivially round-trips), vs. keeping the most-common metadata as the record-level default and only mapping the outliers (terser but ambiguous).

Yeah. If values differ being explicit seems cleaner.
 
>     2. **Per-value tags = replace, not merge** with the record-level list (simpler mental model).

I think that'd be a little hard to reason about so record level tags should apply only when there aren't value level tags, the value-level should be a clean override.

> If this direction sounds reasonable I'm glad to put up a PR with tests. Would you be open to reopening?

It seems reasonable. Main thing left to figure out is how to deal with the complex types.

Otherwise my main concern is that the scope of the changes required stays focused and doesn't impact/complicate the overall provider's code since it's a fairly esoteric use-case.

**Comment by barnumbirr** [comment]
Thanks @ross — replying inline.

> Funnily enough using either a list or dict to store per-value occurred to me while paging this past discussion back into my working memory.

Good to know we landed in the same place independently.

> Yeah. If values differ being explicit seems cleaner.

> I think that'd be a little hard to reason about so record level tags should apply only when there aren't value level tags, the value-level should be a clean override.

Both settled then, and they match what I had in mind: when values differ we emit the full per-value map with no record-level default, and value-level `comment`/`tags` are a clean override — record-level applies only where a value has no entry of its own, no merging.

> I think this is the main issue with keying by the value, it might work decently for simpler/shorter values like the examples, but would get messy quickly with longer TXT values.
>
> The place where it'd more clearly fail (as mentioned later in the Scope section) is with complex multi-part values where there isn't an obvious key, e.g. MX, SRV, ...

> My first thought was to use lists where the comments/tags are matched up by order, but the downside to that would be it's fiddly to make changes and keep things matched up.

Agreed on both. A value-string key falls apart for MX/SRV/… and ordered lists are fiddly exactly as you say. I think there's a form that dodges both: a **list of per-value entries, each restating its value in the same shape it already has in `values:`, matched by value identity rather than position.**

Scalar value (A):

```yaml
bob:
  octodns:
    cloudflare:
      values:
      - value: 151.101.193.10
        comment: primary
        tags: [cdn, tag1]
      - value: 151.101.65.10
        comment: failover
        tags: [cdn, tag2]
  ttl: 300
  type: A
  values: [151.101.193.10, 151.101.65.10]
```

Structured value (MX) — first-class, no stringification needed:

```yaml
aspmx:
  octodns:
    cloudflare:
      values:
      - value: {preference: 10, exchange: aspmx1.example.com.}
        comment: primary MX
        tags: [email]
      - value: {preference: 20, exchange: aspmx2.example.com.}
        comment: backup MX
  ttl: 300
  type: MX
  values:
  - {preference: 10, exchange: aspmx1.example.com.}
  - {preference: 20, exchange: aspmx2.example.com.}
```

Because each entry carries its own value, **order doesn't matter** — you can reorder values freely and nothing misaligns, which is what made the ordered-list version fiddly. Record-level `comment`/`tags` still act as the default for any value without its own entry, so the common "same metadata everywhere" case keeps today's terse shorthand and emits no list at all.

> I don't know that I agree that the structured-value types would be any less likely to have per-value comments or tags.

Fair — I'll drop the scalar-only scope. Because the entry just restates the value in its native shape, structured types are handled by the same code path as scalar ones, so there's no reason to treat them as second-class. One uniform format, all types.

> Off the top of my head i can't think of "normal" situations where values appear multiple times. It'd definitely be possible to create something on purpose like a TXT with the same string multiple times so it is an issue that could be hit.

Right — two entries for the same value is the one genuinely ambiguous case, and only reachable on purpose. The provider keeps the first and logs it, which is the "say something is up" net rather than silent loss.

> It seems reasonable. Main thing left to figure out is how to deal with the complex types.
>
> Otherwise my main concern is that the scope of the changes required stays focused and doesn't impact/complicate the overall provider's code since it's a fairly esoteric use-case.

The list-of-entries form is what resolves the complex types, and it keeps things contained: matching reuses the same value-identity the provider already computes to line records up across a sync (`_gen_key`), so there's no new matching machinery, and the change touches only the read (`_record_for`), write (`_gen_data`), and change-detection (`_extra_changes`) seams rather than spreading through the provider.

If that works for you I'm happy to reopen-and-PR it with full tests, kept tightly scoped to those three seams.
