### ISSUE TITLE
Dot (`.`) in the value of MX record causes the module to freak out

### ISSUE THREAD

**Issue by zajdee** [octodns/octodns-cloudflare#23]
Hi,

we currently have the `.` set as the `MX` records for some of our domains.

```
? ''
: - octodns:
      cloudflare:
        proxied: true
    ttl: 300
    type: ALIAS
    value: some.domain.
  - ttl: 86400
    type: TXT
    value: v=spf1 -all
  - ttl: 86400
    type: MX
    value:
      exchange: .
      preference: 0
```

While retrieving the current values from Cloudflare, octoDNS screams that `..` is not a valid FQDN:
```
2022-07-11T12:53:24  [4620371456] WARNING Record Invalid record testing.domain.
  - Invalid MX exchange ".." is not a valid FQDN.
```

While the Cloudflare API does not usually return records with the trailing dot, there's an exception: if the record only contains a dot and nothing else, the API responds with just the dot:
```
    {
(...)
      "zone_name": "testing.domain",
      "name": "testing.domain",
      "type": "CNAME",
      "content": "some.domain",
(...)
    },
    {
(...)
      "zone_name": "testing.domain",
      "name": "testing.domain",
      "type": "MX",
      "content": ".",
(...)
    },
```

It looks like this line is the culprit:
https://github.com/octodns/octodns-cloudflare/blob/3e8fe9b8bd808cdc7073e27867643f606be1b2bc/octodns_cloudflare/__init__.py#L256

Funny enough, someone already hit this problem with the `SRV` records, as the value of `target` for the `SRV` record is checked for a dot:
https://github.com/octodns/octodns-cloudflare/blob/3e8fe9b8bd808cdc7073e27867643f606be1b2bc/octodns_cloudflare/__init__.py#L275

Apparently there should be checks for `'.'` for all the other records where dot is appended (`CNAME`, `MX` and maybe even `NS`, although I can't imagine a case where someone would place a dot into the value of a `NS` record).
