### ISSUE TITLE
SSHFP support

### ISSUE THREAD

**Issue by deric** [octodns/octodns-cloudflare#37]
Hi,
I'm trying to add some `SSHFP` records that looks like this, the syntax appears to be correct
```
git:
  - type: SSHFP
    values:
      - algorithm: 1
        fingerprint: 859be6ed04643db411f067b6c1da1d75fe08b682
        fingerprint_type: 1
      - algorithm: 1
        fingerprint: da385388bcc7b1b70506a3c4133c2e6366a2fd9819f4718bb3a6e392b9901bfb
        fingerprint_type: 2
```
however with `cloudflare` provider it results into no changes being applied.
```
CloudflareProvider[cloudflare] plan:   No changes
```
In README the `SSHFP` record type is not mentioned, is this supported?
