### ISSUE TITLE
Allow to update comment and/or tag on the record

### ISSUE THREAD

**Issue by stavros-k** [octodns/octodns-cloudflare#41]
Cloudflare supports comments on the records and also tags (on paid tiers)
Would be nice to be able to update them

**Comment by ross** [comment]
Could be done in the CloudflareProvider as a provider-specific thing, e.g.:

```
something:
  octodns:
    cloudflare:
      comment:
      tags:
        - one
        - another
        - a-third
```

I'm not sure if any other providers support tagging, I don't think Route53 does, so this probably makes the most sense. Not opposed to the idea, but won't land high on my priority list.
